spring:
  application:
    name: tsg3macroservice
  kafka:
    bootstrap-servers: "kafka:9092"
    consumer:
      group-id: "my-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.jgc.tsg3macroservice.events.UserEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    username: postgres
    password: password
    url: "jdbc:postgresql://postgresql:5432/tsg3_db"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.time_zone: UTC
event:
  topic:
    name: "TEST_TOPIC"
#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG
        
