spring:
  application:
    name: tsg3macroservice
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "my-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DATABASE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.time_zone: UTC
